---
title: "Bee_Analysis_wNAs"
output: html_document
date: "2024-10-01"
output:
  html_document:
   toc: yes
   toc_float: yes
   collapsed: true 
   smooth_scroll: true
   depth: 2 
   highlight: tango 
   theme: flatly
   code_folding: none
self_contained: yes
mode: selfcontained
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#**Install Packages**
```{r}
install.packages("lme4") # linear mixed effect models
install.packages("ggplot2") # plot graphs
install.packages("tidyverse") # QOL features
install.packages("wesanderson") # color palette
install.packages("dplyr")  # data manipulation
install.packages("BFpack") # Bayes Factor for logistic regression
install.packages("ggThemeAssist") # Add-in to customize ggplot2 themes
install.packages("performance") # For assumption checking
install.packages("DHARMa") # For assumption checking
install.packages("patchwork")
install.packages("lmerTest")
```

# **Load Packages**
```{r, message=FALSE, warning=FALSE}
library(lme4) # linear mixed effect models
library(ggplot2) # plot graphs
library(tidyverse) # QOL features
library(wesanderson) # color palette
library(dplyr)  # data manipulation
library(BFpack) # Bayes Factor for logistic regression
library(ggThemeAssist) # you may need to restart you session for this add-in to appear
library(performance) # For assumption checking
library(DHARMa) # For assumption checking
library(tidyr)
library(patchwork)
library(lmerTest)
library(readr)
```

#**Load Data**
```{r}
beesNA <- read.csv("../Data/bees_wNA.csv", header = TRUE)
view(beesNA)
summary(beesNA) #view summary
str(beesNA) #display structure
```
#**Wrangle Data**
```{r}
beesNA$individual <- as.factor(beesNA$individual)
beesNA$type <- as.factor(beesNA$type)
beesNA$species <- as.factor(beesNA$species)
beesNA$urban_gradient <- as.factor(beesNA$urban_gradient)
beesNA$temperature <- as.factor(beesNA$temperature)
beesNA$light <- as.factor(beesNA$light)
beesNA$condition <- as.factor(beesNA$condition)
beesNA$condition2 <- as.factor(beesNA$condition2)
beesNA$condition_sequence <- as.factor(beesNA$condition_sequence)
str(beesNA)
```
#**Check Levels**
```{r}
levels(beesNA$type)
levels(beesNA$urban_gradient)
levels(beesNA$temperature)
levels(beesNA$species)
levels(beesNA$light)
levels(beesNA$condition)
levels(beesNA$condition2)
```
# **Visualise Shape**
```{r}
ggplot(data = beesNA, aes(x = condition, y = duration_from_start, colour = type)) +
  geom_boxplot() +
  labs(x = "Light", y = "Time to Complete (s)") +
  theme_classic() +
  theme(plot.title = element_text(size = 11))    
```
#**Modelling**
```{r}

beesNA_m1 <- lmer(duration_from_start~ urban_gradient*temperature*light + type*temperature + type*light + type +   (1|individual), data = beesNA)
summary(beesNA_m1)
AIC(beesNA_m1)

```

#**Check Assumptions**
```{r}
acf(residuals(beesNA_m1)) # check for independence of residuals - there should be no increasing or decreasing pattern and should look noisy

qqnorm(residuals(beesNA_m1))
qqline(residuals(beesNA_m1))  # Normality of residuals


plot(fitted(beesNA_m1), residuals(beesNA_m1))   # Homoscedasticity assumption, there should be no fanning pattern

simulated_residuals <- simulateResiduals(fittedModel = beesNA_m1) # additional test from DHARMA
plot(simulated_residuals)
```

#**Transform Data**
```{r}
beesNA$transformed_duration <- log(beesNA$duration_from_start)

# Full model
beesNA_m3 <- lmer(transformed_duration~ urban_gradient*temperature*light + type*temperature + type*light + (1|individual), data = beesNA)
AIC(beesNA_m3)
summary(beesNA_m3)

# Simplify further
beesNA_m4 <- lmer(transformed_duration~ light + urban_gradient*temperature + type*temperature + (1|individual), data = beesNA)
AIC(beesNA_m4)
summary(beesNA_m4)
```

#**Check Assumptions**
```{r}
acf(residuals(beesNA_m4)) # check for independence of residuals - there should be no increasing or decreasing pattern and should look noisy

qqnorm(residuals(beesNA_m4))
qqline(residuals(beesNA_m4))  # Normality of residuals


plot(fitted(beesNA_m4), residuals(beesNA_m4))   # Homoscedasticity assumption, there should be no fanning pattern

simulated_residuals <- simulateResiduals(fittedModel = beesNA_m4) # additional test from DHARMA
plot(simulated_residuals)
```

#**Visualise by Group**
```{r}

summary_bees <- beesNA %>%
  group_by(condition2, type) %>%
  mutate(
    mean = mean(transformed_duration),
    individual = as.factor(individual),
    n = n(),
    se = sd(transformed_duration) / sqrt(n),
    ci95 = qt(0.975, df = n - 1) * se,   # 95% CI multiplier
    ci_low = mean - ci95,
    ci_high = mean + ci95
  ) %>%
  ungroup()

summary_bees <- summary_bees %>%
  mutate(transformed_duration = ifelse(transformed_duration < 0, 0.01, transformed_duration))

fig3 <- ggplot(summary_bees, aes(x = condition2, y = transformed_duration)) +
  geom_col(aes(y = mean, fill = type), size = 4, position = position_dodge(0.9)) +
  geom_jitter(
  aes(fill = type, group = type),  # fill/type gives dodging reference
  position = position_jitterdodge(jitter.width = 0.01, dodge.width = 0.9),
  show.legend = FALSE,
  size = 0.7,
  colour = "grey50"  # fixed display colour
) +
  geom_errorbar(
    aes(ymin = ci_low, ymax = ci_high, group = type),
    position = position_dodge(0.9), width = 0.15, colour = "black"
  ) +
  scale_colour_manual(values = wes_palette("Darjeeling1", length(unique(summary_bees$individual)), type = "continuous")) +
  scale_fill_manual(values = c(
    "Honeybees" = "#D9A94D",
    "Native" = "#A1B5D8"
  )) +
  labs(
    x = "Condition (ºC / Light / Urban Gradient)",
    y = "Mean log duration (in seconds from start)",
    fill = "Species"
  ) +
  theme(legend.position = "right") +
  theme_minimal(base_family = "") +
  guides(fill = guide_legend(title = "Taxa")) +
  theme(
    plot.background = element_rect(fill = "white"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(color = "black"),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12),
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 12),
    plot.margin = margin(0.8, 0.8, 0.8, 0.8, "cm"),
    axis.title.x = element_text(vjust = -4),
    axis.title.y = element_text(vjust = 6),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 5))
print(fig3)


ggsave(fig3, width = 8, height = 6, dpi = 300, filename = "../Output/fig3.pdf")
ggsave(fig3, width = 8, height = 6, dpi = 300, filename = "../Output/fig3.png")

```
#** Interaction effect graph**
```{r}
ggplot(beesNA, aes(x = temperature, y = transformed_duration, color = type, group = type)) +
  geom_smooth(method = "lm", se = TRUE, aes(color = type)) +  # Add regression lines with confidence intervals
  labs(title = "Interaction between Temperature and Bee Type",
       x = "Temperature (32 vs. 28)",
       y = "Response Variable",
       color = "Bee Type") +
  theme_minimal()
```


#**Means**
```{r}

mean_duration <- beesNA %>%
  group_by(type, temperature) %>%
  summarise(mean = mean(duration_from_start, na.rm = TRUE))
print(mean_duration)
```

#**Figure 4 revision - reviewer
```{r}

beesNA$transformed_duration <- log(beesNA$duration_from_start)

# Summarise by temperature and type
summary_bees <- beesNA %>%
  group_by(temperature, type) %>%
  mutate(
    mean = mean(transformed_duration),
    individual = as.factor(individual),
    n = n(),
    se = sd(transformed_duration) / sqrt(n),
    ci = qt(0.975, df = n - 1) * se  # 95% CI
  )

# Ensure no negative values
summary_bees <- summary_bees %>%
  mutate(transformed_duration = ifelse(transformed_duration < 0, 0.01, transformed_duration))

# Plot
fig4 <- ggplot(summary_bees, aes(x = temperature, y = transformed_duration)) +
  geom_col(
    aes(y = mean, fill = type),
    size = 4,
    position = position_dodge(0.9)
  ) +
 geom_jitter(
  aes(fill = type, group = type),  # fill/type gives dodging reference
  position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.9),
  show.legend = FALSE,
  size = 0.7,
  colour = "grey50"  # fixed display colour
) +
  geom_errorbar(
    aes(ymin = mean - ci, ymax = mean + ci, group = type),
    position = position_dodge(0.9),
    width = 0.15,
    colour = "black"
  ) +
  scale_colour_manual(
    values = wes_palette("Darjeeling1", length(unique(summary_bees$individual)), type = "continuous")
  ) +
  scale_fill_manual(values = c("Honeybees" = "#D9A94D", "Native" = "#A1B5D8")) +
  labs(
    x = "Temperature (ºC)",
    y = "Mean log (duration in seconds from start)",
    fill = "Species"
  ) +
  theme_minimal(base_family = "") +
  theme(
    legend.position = "right",
    plot.background = element_rect(fill = "white"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(color = "black"),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12),
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 12),
    plot.margin = margin(0.8, 0.8, 0.8, 0.8, "cm"),
    axis.title.x = element_text(vjust = -4),
    axis.title.y = element_text(vjust = 6),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 5))

print(fig4)
ggsave(fig4, width = 8, height = 6, dpi = 300, filename = "../Output/fig4.pdf")
ggsave(fig4, width = 8, height = 6, dpi = 300, filename = "../Output/fig4.png")
```

#** Native
```{r}
beesNA <- beesNA %>%
  mutate(
    genus = case_when(
      species == "Apis mellifera" ~ "Apis",
      species == "Lasioglossum (Chilalictus)" ~ "Lasioglossum",
      species == "Lasioglossum (Parasphecodes)" ~ "Lasioglossum",
      species == "Lasioglossum (Homalictus)" ~ "Lasioglossum",
      species == "Lasioglossum" ~ "Lasioglossum",
      species == "Exoneura" ~ "Exoneura",
      species == "Leioproctus" ~ "Leioproctus",
      species == "Native" ~ "Native (Unknown genus)",
      TRUE ~ NA_character_  # Fill with NA for any other species
    )
  )


beesNA_reviewfull <- lmer(transformed_duration~ urban_gradient*temperature*light + genus*temperature + genus*light + (1|individual), data = beesNA)
AIC(beesNA_reviewfull)
summary(beesNA_reviewfull)



beesNA_review <- lmer(transformed_duration~ light + urban_gradient*temperature + genus*temperature + (1|individual), data = beesNA)
AIC(beesNA_review)
summary(beesNA_review)

# Summarise by temperature and type
summary_bees_review <- beesNA %>%
  group_by(temperature, genus) %>%
  mutate(
    mean = mean(transformed_duration),
    individual = as.factor(individual),
    n = n(),
    se = sd(transformed_duration) / sqrt(n),
    ci = qt(0.975, df = n - 1) * se  # 95% CI
  )

# Ensure no negative values
summary_bees_review <- summary_bees_review %>%
  mutate(transformed_duration = ifelse(transformed_duration < 0, 0.01, transformed_duration))

# Plot
fig_genus <- ggplot(summary_bees_review, aes(x = temperature, y = transformed_duration)) +
  geom_col(
    aes(y = mean, fill = genus),
    size = 4,
    position = position_dodge(0.9)
  ) +
  geom_jitter(
    aes(colour = individual, group = genus),
    position = position_jitterdodge(jitter.width = .5, dodge.width = 0.9),
    show.legend = FALSE,
    size = 0.7
  ) +
  geom_errorbar(
    aes(ymin = mean - ci, ymax = mean + ci, group = genus),
    position = position_dodge(0.9),
    width = 0.15,
    colour = "black"
  ) +
  scale_colour_manual(
    values = wes_palette("Darjeeling1", length(unique(summary_bees$individual)), type = "continuous")
  ) +
  labs(
    x = "Temperature (ºC)",
    y = "Mean log (duration in seconds from start)",
    fill = "Genus"
  ) +
  theme_minimal(base_family = "") +
  theme(
    legend.position = "right",
    plot.background = element_rect(fill = "white"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(color = "black"),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12),
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 12),
    plot.margin = margin(0.8, 0.8, 0.8, 0.8, "cm"),
    axis.title.x = element_text(vjust = -4),
    axis.title.y = element_text(vjust = 6),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  scale_y_continuous(expand = c(0, 0))

print(fig_genus)

ggsave(fig_genus, width = 8, height = 6, dpi = 300, filename = "../Output/figgenus.pdf")
ggsave(fig_genus, width = 8, height = 6, dpi = 300, filename = "../Output/figgenus.png")


#Remove Exonueura and leioproctus

beesNA_filtered <- beesNA %>%
  filter(!species %in% c("Exoneura", "Leioproctus", "Native (Unknown genus)", "Native"))

beesNA_filtered_fulllm <- lmer(transformed_duration~ urban_gradient*temperature*light + type*temperature + type*light + (1|individual), data = beesNA_filtered)
AIC(beesNA_filtered_fulllm)
summary(beesNA_filtered_fulllm)

beesNA_filtered_lm <- lmer(transformed_duration~ light + urban_gradient*temperature + type*temperature + (1|individual), data = beesNA_filtered)
summary(beesNA_filtered_lm)

# Remove 120 seconds bees that failed

beesNA_success <- beesNA %>%
  filter(!duration_from_start %in% c("120"))

beesNA_success_lmfull <- lmer(transformed_duration~ urban_gradient*temperature*light + type*temperature + type*light + (1|individual), data = beesNA_success)
summary(beesNA_success_lmfull)

beesNA_success_lmfull <- lmer(transformed_duration~ light + urban_gradient*temperature + type*temperature + (1|individual), data = beesNA_success)
summary(beesNA_filtered_lm)


# Proportion graph

# Example assuming your data frame is called df
beesNA_summary <- beesNA %>%
  mutate(
    duration_flag = ifelse(duration_from_start == 120, "120", "Other"),
    condition = case_when(
      temperature == 28 & type == "Native"   ~ "Temp 28 - Native",
      temperature == 32 & type == "Native"   ~ "Temp 32 - Native",
      temperature == 28 & type == "Honeybees" ~ "Temp 28 - Honeybee",
      temperature == 32 & type == "Honeybees" ~ "Temp 32 - Honeybee"
    )
  ) %>%
  group_by(condition, duration_flag) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(condition) %>%
  mutate(prop = count / sum(count))

# Plot
ggplot(beesNA_summary, aes(x = condition, y = prop, fill = duration_flag)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values = c("120" = "grey40", "Other" = "grey80")) +
  labs(
    x = "Condition",
    y = "Proportion",
    fill = "Duration",
    title = "Proportion of Individuals with Duration 120 vs. Other"
  ) +
  theme_minimal()


df_summary <- beesNA %>%
  mutate(duration_flag = ifelse(duration_from_start == 120, "120", "Other")) %>%
  group_by(type, duration_flag) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(type) %>%
  mutate(prop = count / sum(count))
```

